
#!/bin/bash
#PBS -l select=1:ncpus=24:mpiprocs=24
#PBS -l walltime=96:00:00
#PBS -q smp
#PBS -P CBBI1243
#PBS -o /mnt/lustre/groups/CBBI1243/KEVIN/mds/gjb4_wt/stdout.txt
#PBS -e /mnt/lustre/groups/CBBI1243/KEVIN/mds/gjb4_wt/stderr.txt
#PBS -m b
#PBS -N Gromacs_GJB4.B99990026
#PBS -M kevin.esoh@students.jkuat.ac.ke

#MODULEPATH=/opt/gridware/bioinformatics/modules:$MODULEPATH
#source /etc/profile.d/modules.sh

### # module add/load # ###
module add chpc/BIOMODULES
module load gromacs/5.1.4-openmpi_1.10.2-intel16.0.1
module load R/3.6.0-gcc7.2.0

#OMP_NUM_THREADS=1 #turn off OpenMP (also -ntomp on commandline)

#-nt -ntmpi number of threads and number of mpi threads

NP=`cat ${PBS_NODEFILE} | wc -l`
#NP=24
echo "Number of Processes: $NP"

mdr="gmx_mpi mdrun"
#ARGS="-s X -deffnm Y"

cd /mnt/lustre/groups/CBBI1243/KEVIN/mds/gjb4_wt/
#mpirun -np ${NP} -machinefile ${PBS_NODEFILE} ${mdr} ${ARGS}

# Remove water molecules (crystal)
grep -v "HOH" GJB4.B99990026.pdb > GJB4.B99990026_clean.pdb

# Create required files; topology, position restraint, post-processed structure
echo 15 | gmx_mpi pdb2gmx -f GJB4.B99990026_clean.pdb -o GJB4.B99990026_processed.gro -water spce

# Define unit cell & add solvent
gmx_mpi editconf -f GJB4.B99990026_processed.gro -o GJB4.B99990026_newbox.gro -c -d 1.0 -bt cubic
gmx_mpi solvate -cp GJB4.B99990026_newbox.gro -cs spc216.gro -o GJB4.B99990026_solv.gro -p topol.top
gmx_mpi grompp -f ions.mdp -c GJB4.B99990026_solv.gro -p topol.top -o ions.tpr
echo 13 | gmx_mpi genion -s ions.tpr -o GJB4.B99990026_solv_ions.gro -p topol.top -pname NA -nname CL -neutral

# Energy minimization
gmx_mpi grompp -f minim.mdp -c GJB4.B99990026_solv_ions.gro -p topol.top -o em.tpr
time ${mdr} -v -cpi -maxh 72 -ntomp ${NP} -deffnm em #gmx mdrun
echo -e "Potential\n0" | gmx_mpi energy -f em.edr -o GJB4.B99990026_potential.xvg
grep -v -e "#" -e "@" GJB4.B99990026_potential.xvg > GJB4.B99990026_potential.txt

# Equilibration Phase 1: NVT (Energy and Temperature)
gmx_mpi grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr
time ${mdr} -v -maxh 72 -ntomp ${NP} -deffnm nvt #gmx mdrun
echo -e "Temperature\n0" | gmx_mpi energy -f nvt.edr -o GJB4.B99990026_temperature.xvg
grep -v -e "#" -e "@" GJB4.B99990026_temperature.xvg > GJB4.B99990026_temperature.txt

# Equilibration Phase 2: NPT (Pressure and Density)
gmx_mpi grompp -f npt.mdp -c nvt.gro -r nvt.gro -t nvt.cpt -p topol.top -o npt.tpr
time ${mdr} -v -maxh 72 -ntomp ${NP} -deffnm npt #gmx mdrun
echo -e "Pressure\n0" | gmx_mpi energy -f npt.edr -o GJB4.B99990026_pressure.xvg
grep -v -e "#" -e "@" GJB4.B99990026_pressure.xvg > GJB4.B99990026_pressure.txt
echo -e "Density\n0" | gmx_mpi energy -f npt.edr -o GJB4.B99990026_density.xvg
grep -v -e "#" -e "@" GJB4.B99990026_density.xvg > GJB4.B99990026_density.txt

# Run Production MD
gmx_mpi grompp -f md.mdp -c npt.gro -t npt.cpt -p topol.top -o md_0_1.tpr
time ${mdr} -v -maxh 72 -ntomp ${NP} -deffnm md_0_1 #gmx mdrun

# Analysis
echo 1 0 | gmx_mpi trjconv -s md_0_1.tpr -f md_0_1.xtc -o md_0_1_noPBC.xtc -pbc mol -center
echo 4 4 | gmx_mpi rms -s md_0_1.tpr -f md_0_1_noPBC.xtc -o rmsd.xvg -tu ns
grep -v -e "#" -e "@" rmsd.xvg > rmsd.txt

echo 4 4 | gmx_mpi rms -s em.tpr -f md_0_1_noPBC.xtc -o rmsd_xtal.xvg -tu ns
grep -v -e "#" -e "@" rmsd_xtal.xvg > rmsd_xtal.txt

echo 1 | gmx_mpi gyrate -s md_0_1.tpr -f md_0_1_noPBC.xtc -o gyrate.xvg
grep -v -e "#" -e "@" gyrate.xvg > gyrate.txt

#gmx_mpi rama -f em.gro -s em.tpr -o ramachan.xvg # Ramachandran Plot for crystal struct


# Generate plots
Rscript /mnt/lustre/groups/CBBI1243/KEVIN/mds/plot.R GJB4.B99990026_potential.txt GJB4.B99990026_temperature.txt GJB4.B99990026_pressure.txt GJB4.B99990026_density.txt rmsd.txt rmsd_xtal.txt gyrate.txt gyrate.txt
      
