
#!/bin/bash
#PBS -l select=1:ncpus=24:mpiprocs=24
#PBS -l walltime=96:00:00
#PBS -q smp
#PBS -P CBBI1243
#PBS -o /mnt/lustre/groups/CBBI1243/KEVIN/mds/gjb4_wt/stdout.txt
#PBS -e /mnt/lustre/groups/CBBI1243/KEVIN/mds/gjb4_wt/stderr.txt
#PBS -m b
#PBS -N Gromacs_GJB4.B99990026
#PBS -M kevin.esoh@students.jkuat.ac.ke

#MODULEPATH=/opt/gridware/bioinformatics/modules:$MODULEPATH
#source /etc/profile.d/modules.sh

### # module add/load # ###
module add chpc/BIOMODULES
module load gromacs/5.1.4-openmpi_1.10.2-intel16.0.1
module load R/3.6.0-gcc7.2.0

#OMP_NUM_THREADS=1 #turn off OpenMP (also -ntomp on commandline)

#-nt -ntmpi number of threads and number of mpi threads

NP=`cat ${PBS_NODEFILE} | wc -l`
#NP=24
echo "Number of Processes: $NP"

mdr="gmx_mpi mdrun"
#ARGS="-s X -deffnm Y"

cd /mnt/lustre/groups/CBBI1243/KEVIN/mds/gjb4_wt/
#mpirun -np ${NP} -machinefile ${PBS_NODEFILE} ${mdr} ${ARGS}

# Run Production MD
time ${mdr} -s md_0_1 -v -maxh 96 -ntomp ${NP} -cpi md_0_1 #gmx mdrun

## Analysis
#echo 1 0 | gmx_mpi trjconv -s md_0_1.tpr -f md_0_1.xtc -o md_0_1_noPBC.xtc -pbc mol -center
#echo 4 4 | gmx_mpi rms -s md_0_1.tpr -f md_0_1_noPBC.xtc -o rmsd.xvg -tu ns
#grep -v -e "#" -e "@" rmsd.xvg > rmsd.txt
#
#echo 4 4 | gmx_mpi rms -s em.tpr -f md_0_1_noPBC.xtc -o rmsd_xtal.xvg -tu ns
#grep -v -e "#" -e "@" rmsd_xtal.xvg > rmsd_xtal.txt
#
#echo 1 | gmx_mpi gyrate -s md_0_1.tpr -f md_0_1_noPBC.xtc -o gyrate.xvg
#grep -v -e "#" -e "@" gyrate.xvg > gyrate.txt
#
##gmx_mpi rama -f em.gro -s em.tpr -o ramachan.xvg # Ramachandran Plot for crystal struct
#
#
## Generate plots
#Rscript /mnt/lustre/groups/CBBI1243/KEVIN/mds/plot.R GJB4.B99990030_potential.txt GJB4.B99990030_temperature.txt GJB4.B99990030_pressure.txt GJB4.B99990030_density.txt rmsd.txt rmsd_xtal.txt gyrate.txt gyrate.txt
      
